name: Print Secrets

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    name: Print Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Values
        run: |
          env | grep -i secret_ | awk -F "=" '{print $1, $2}' | while read -r name value; do
            echo "$name: $value"
          done
