name: Deploy Medrecs Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: 
      name: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          NAME: ${{ secrets.NAME }}
        run: echo "$MY_SECRET6"

      - name: Run JavaScript
        run: node index.js
