name: Deploy Medrecs Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: staging
    steps:
      - name: Set up environment
        env:
          MY_SECRET1: ${{ secrets.TEST }}
          MY_SECRET2: '${{ secrets.staging.STAGINGVALUE }}'
          MY_SECRET3: '${{ secrets.STAGING.STAGINGVALUE }}'
        run: |
          echo "$MY_SECRET1 || $MY_SECRET2 || $MY_SECRET3 "
