name: Deploy Medrecs Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Show secrets
        run: |
          echo "$GITHUB_ENV" >> $GITHUB_ENV
          env | grep -i secret_ | awk -F "=" '{print $1}' | while read -r line; do
            echo "$line=${{ env[$line] }}" >> $GITHUB_ENV
          done
          echo "::add-mask::$GITHUB_ENV"
          echo "Secrets:"
          cat $GITHUB_ENV | jq -R 'fromjson? | select(type == "object")'